name: Open a PR to master

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  MESSAGE: Merge branch `${{ github.head_ref || github.ref_name }}` to `master`

jobs:
  pull-request:
    name: Open pull request
    runs-on: ubuntu-latest
    permissions:                      # ← AÑADE ESTO
      contents: write                 # Necesario para crear la referencia del PR
      pull-requests: write            # Necesario para crear el PR
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Open pull request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: master
          pr_title: 'chore: ${{ env.MESSAGE }}'
          pr_body: |
            This pull request will ${{ env.MESSAGE }}.
          pr_draft: true
          github_token: ${{ secrets.EXTEN_TOKEN }}   # Opcional, pero explícito
