name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    permissions:
      contents: write
      packages: write          # Necesario para publicar en GitHub Packages
      # Si usas GITHUB_TOKEN en lugar de un PAT, añade también: packages: read
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # opcional
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v3

      - name: Get the version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update version in gradle.properties
        run: |
          sed -i "s/^version=.*/version=${{ steps.get_version.outputs.VERSION }}/" gradle.properties

      - name: Build and generate patches
        run: |
          ./gradlew generatePatchesFiles
          ./gradlew jar
        env:
          # Estas variables de entorno serán usadas por settings.gradle.kts
          # para autenticarse en los repositorios privados de GitHub Packages
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.EXTEN_TOKEN }}   # Reemplaza EXTEN_TOKEN por el secreto que tengas

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "lts/*"
          cache: 'npm'

      - name: Install dependencies (si las necesitas)
        run: npm install

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          fingerprint: ${{ vars.GPG_FINGERPRINT }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            patches/build/libs/*.EXRE
            patches-exre.json
        env:
          GITHUB_TOKEN: ${{ secrets.EXTEN_TOKEN }}

      - name: Publish to GitHub Packages
        run: ./gradlew :patches:publish
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.EXTEN_TOKEN }}